CREATE DATABASE CORPORATIONLIBROS
GO

USE CORPORATIONLIBROS
GO

CREATE TABLE EDITORIALES(
PK_CODIGOEDITORIAL INT NOT NULL,
CONSTRAINT [PK_EDITORIALES]
PRIMARY KEY (PK_CODIGOEDITORIAL),
NOMBRE VARCHAR (100) NOT NULL,
PAISORIGEN VARCHAR (100) NOT NULL,
)
GO

CREATE TABLE LIBROS (
PK_CODIGOLIBRO INT NOT NULL,
CONSTRAINT [PK_LIBRO_CODIGOLIBRO]
PRIMARY KEY (PK_CODIGOLIBRO),
TITULO VARCHAR (100) NULL,
ISBN INT NOT NULL,
DESCRIPCION VARCHAR (500) NOT NULL,
NROPAGINAS VARCHAR (50) NOT NULL,
PUBLICACIONES VARCHAR (50) NOT NULL,
FK_CODIGOEDITORIAL INT NOT NULL,
CONSTRAINT [FK_LIBROS_EDITORES_CODIGOEDITORIAL]
FOREIGN KEY (FK_CODIGOEDITORIAL)
REFERENCES EDITORIALES(PK_CODIGOEDITORIAL),
)
GO

CREATE TABLE AUTORESLIBROS (
FK_CODIGOLIBRO INT NOT NULL,
CONSTRAINT [FK_EJEMPLARES_LIBROS_CODIGOLIBRO]
FOREIGN KEY (FK_CODIGOLIBRO)
REFERENCES LIBROS(PK_CODIGOLIBRO),
FK_CODIGOAUTOR INT NOT NULL,
CONSTRAINT [FK_EJEMPLARES_AUTORES_CODIGOAUTOR]
FOREIGN KEY (FK_CODIGOAUTOR)
REFERENCES AUTORES (PK_CODIGOAUTOR),
)
GO

CREATE TABLE EJEMPLARE (
FK_CODIGOLIBRO INT NOT NULL,
CONSTRAINT [FK_EJEMPLARES_LIBROS_CODIGOLIBRO]
FOREIGN KEY (FK_CODIGOLIBRO)
REFERENCES LIBROS (PK_CODIGOLIBRO),
UBICACION VARCHAR (100) NOT NULL,
ESTADOSOLICITUD VARCHAR (100) NULL,
)
GO

CREATE TABLE AUTORES (
PK_CODIGOAUTOR INT NOT NULL,
CONSTRAINT [PK_AUTORES]
PRIMARY KEY (PK_CODIGOAUTOR),
NOMBRECOMPLETO VARCHAR (200) NOT NULL,
APELLIDO VARCHAR (200) NOT NULL,
PAISORIGEN VARCHAR (100) NOT NULL,
)
GO




